// <copyright file="CloudVariables.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using CloudPrefs;

    /// <summary>
    /// Provides access to cloud variables registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudVariables
    {
        private static readonly CloudBool s_unlimitedUndos = new CloudBool("UnlimitedUndos", PersistenceType.Latest, false);

        public static bool UnlimitedUndos
        {
            get { return s_unlimitedUndos.Value; }
            set { s_unlimitedUndos.Value = value; }
        }

        private static readonly CloudCurrencyInt s_undos = new CloudCurrencyInt("Undos", 0, false);

        public static int Undos
        {
            get { return s_undos.Value; }
            set { s_undos.Value = value; }
        }

        private static readonly CloudInt s_highScore = new CloudInt("HighScore", PersistenceType.Highest, 0);

        public static int HighScore
        {
            get { return s_highScore.Value; }
            set { s_highScore.Value = value; }
        }
    }
}
