// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_high_Score = new UnifiedLeaderboard("High_Score",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI37zJ85kBEAIQAA"
#else
            "High_Score"
#endif
            );

        public static UnifiedLeaderboard High_Score
        {
            get { return s_high_Score; }
        }

        private static readonly UnifiedLeaderboard s_highest_Score_Before_Board_Clear = new UnifiedLeaderboard("Highest_Score_Before_Board_Clear",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            ""
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI37zJ85kBEAIQBA"
#else
            "Highest_Score_Before_Board_Clear"
#endif
            );

        public static UnifiedLeaderboard Highest_Score_Before_Board_Clear
        {
            get { return s_highest_Score_Before_Board_Clear; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "High_Score", s_high_Score },
            { "Highest_Score_Before_Board_Clear", s_highest_Score_Before_Board_Clear },
        };
    }
}
